// <auto-generated />
namespace Crud_Operation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Account_with_dbset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Account_with_dbset));
        
        string IMigrationMetadata.Id
        {
            get { return "202304130612221_add_Account_with_dbset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
