// <auto-generated />
namespace Crud_Operation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Product_list : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Product_list));
        
        string IMigrationMetadata.Id
        {
            get { return "202304050547262_add_Product_list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
